//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Msm.Core.Assets.Internationalization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Translations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Translations() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Msm.Core.Assets.Internationalization.Translations", typeof(Translations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Called by `{0}`..
        /// </summary>
        internal static string Assertion_Caller {
            get {
                return ResourceManager.GetString("Assertion_Caller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For expression `{0}`..
        /// </summary>
        internal static string Assertion_Expression {
            get {
                return ResourceManager.GetString("Assertion_Expression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In file `{0}`..
        /// </summary>
        internal static string Assertion_File {
            get {
                return ResourceManager.GetString("Assertion_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At line `{0}`..
        /// </summary>
        internal static string Assertion_Line {
            get {
                return ResourceManager.GetString("Assertion_Line", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instance of `{0}` is null..
        /// </summary>
        internal static string Assertion_TypeCategory {
            get {
                return ResourceManager.GetString("Assertion_TypeCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The body of `{0}` should be a `{1}`, instead it&apos;s `{2}`..
        /// </summary>
        internal static string ExpressionBodyIsNotMemberExpression {
            get {
                return ResourceManager.GetString("ExpressionBodyIsNotMemberExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to parse AppSettings key `{0}`..
        /// </summary>
        internal static string FailedToParseAppSettingsKey {
            get {
                return ResourceManager.GetString("FailedToParseAppSettingsKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input `{0}` and output `{1}` types are different..
        /// </summary>
        internal static string InputAndOutputTypeAreDifferent {
            get {
                return ResourceManager.GetString("InputAndOutputTypeAreDifferent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameterless constructor not found for type `{0}`..
        /// </summary>
        internal static string ParameterlessConstructorNotFoundForType {
            get {
                return ResourceManager.GetString("ParameterlessConstructorNotFoundForType", resourceCulture);
            }
        }
    }
}
