//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Msm.Gui.Assets.Internationalization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Translations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Translations() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Msm.Gui.Assets.Internationalization.Translations", typeof(Translations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Msm.Gui.
        /// </summary>
        public static string AppDisplayName {
            get {
                return ResourceManager.GetString("AppDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main.
        /// </summary>
        public static string MainPageTitle {
            get {
                return ResourceManager.GetString("MainPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TEMP_MainWindowTitle.
        /// </summary>
        public static string MainWindowTitle {
            get {
                return ResourceManager.GetString("MainWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page key `{0}` is null or white space..
        /// </summary>
        public static string PageKeyIsNullOrWhiteSpace {
            get {
                return ResourceManager.GetString("PageKeyIsNullOrWhiteSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page not found: `{0}`. Did you forget to call PageService.Configure?.
        /// </summary>
        public static string PageNotFound {
            get {
                return ResourceManager.GetString("PageNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main.
        /// </summary>
        public static string ShellMenuItemViewsMainPageHeader {
            get {
                return ResourceManager.GetString("ShellMenuItemViewsMainPageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common Group 1.
        /// </summary>
        public static string ShellPageRibbonHomeGroupCommon1Header {
            get {
                return ResourceManager.GetString("ShellPageRibbonHomeGroupCommon1Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common Group 2.
        /// </summary>
        public static string ShellPageRibbonHomeGroupCommon2Header {
            get {
                return ResourceManager.GetString("ShellPageRibbonHomeGroupCommon2Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string ShellPageRibbonTabHomeHeader {
            get {
                return ResourceManager.GetString("ShellPageRibbonTabHomeHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The key `{0}` is already configured in page service..
        /// </summary>
        public static string TheKeyIsAlreadyConfiguredInPageService {
            get {
                return ResourceManager.GetString("TheKeyIsAlreadyConfiguredInPageService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The page is already registered with key `{0}`..
        /// </summary>
        public static string ThePageTypeIsAlreadyRegisteredWithKey {
            get {
                return ResourceManager.GetString("ThePageTypeIsAlreadyRegisteredWithKey", resourceCulture);
            }
        }
    }
}
